// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enrvndbuenycppgfltcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVucnZuZGJ1ZW55Y3BwZ2ZsdGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDA4ODgsImV4cCI6MjA2Mzk3Njg4OH0.oKyMPvevd7iMnpCscfIlxQlrYiQ08lte2FweLo3i8hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);